- set_fact:
    _qemu_binfmt_ns: "{{cfg_values.namespace|default('kube-system')}}"

- name: remove qemu-user-static DaemonSet
  kubernetes.core.k8s:
    kubeconfig: "{{_k3s_kubecfg}}"
    state: absent
    definition:
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: qemu-user-static
        namespace: "{{_qemu_binfmt_ns}}"
